### PR TITLE
Fix crash caused by Not allowed to start service

### PR DESCRIPTION
**Pull request by tangjingyuan**
# This PR contains the tow following changes:

## 1. Fix crash caused by java.lang.IllegalStateException: Not allowed to start service Intent.
This crash is easily to recreate in users's Android O devices and mine. It happens after installation. Here is the log:

Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.quoord.tapatalkpro.activity/com.openlocate.android.core.LocationService (has extras) }: app is in background uid UidRecord{b90c40 u0a710 CEM  idle procs:2 seq(0,0,0)}
&nbsp;&nbsp;&nbsp;&nbsp;at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
&nbsp;&nbsp;&nbsp;&nbsp;at android.app.ContextImpl.startService(ContextImpl.java:1484)
&nbsp;&nbsp;&nbsp;&nbsp;at android.content.ContextWrapper.startService(ContextWrapper.java:663)
&nbsp;&nbsp;&nbsp;&nbsp;at com.openlocate.android.core.OpenLocate.initialize(Unknown Source:66)
&nbsp;&nbsp;&nbsp;&nbsp;at com.openlocate.android.core.OpenLocate$2.onAdvertisingInfoTaskExecute(Unknown Source:2)
&nbsp;&nbsp;&nbsp;&nbsp;at com.openlocate.android.core.FetchAdvertisingInfoTask.onPostExecute(Unknown Source:13)
&nbsp;&nbsp;&nbsp;&nbsp;at android.os.AsyncTask.finish(AsyncTask.java:695)
&nbsp;&nbsp;&nbsp;&nbsp;at android.os.AsyncTask.-wrap1(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
&nbsp;&nbsp;&nbsp;&nbsp;at android.os.Handler.dispatchMessage(Handler.java:105)

## 2. Update README.md
According to the [LocationProvider](https://github.com/OpenLocate/openlocate-android/blob/06e1987355962e29835897004bc8c2e7071c8a83/openlocate/src/main/java/com/openlocate/android/core/LocationProvider.java#L30-L33), the value of location_method will only be among gps, network, passive.

@kurabi Please review.

### CODE REVIEW

**Comment by kurabi** [comment]
Thanks for the PR. I installed the included Example app on an Android O device and this crash does not occur. Can you provide more details as to how to reproduce this crash? Are you using a different Target API level in your app? It’s 25 in the example app.

**Comment by tangjingyuan** [comment]
@kurabi The target API level is 26. We upgraded the OpenLocate to 1.1.11 and enabled it for Android O devices again in our beta channel.

The beta users told us the crash happened after app upgraded.

In my Samsung S8+ (Android 8.0.0), the crash happens when I build in AndroidStudio. I found it's more easily to occur when the device's battery is low. When the battery is high, it's hardly to see the crash.

It seems the OS limit the app's ability to start service when battery is low.

**Comment by tangjingyuan** [comment]
@kurabi Here is the log in AndroidStudio:

04-12 23:33:14.414 4631-4631/com.quoord.tapatalkpro.activity E/AndroidRuntime: FATAL EXCEPTION: main Process: com.quoord.tapatalkpro.activity, PID: 4631

java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.quoord.tapatalkpro.activity/com.openlocate.android.core.LocationService (has extras) }: app is in background uid UidRecord{5e7ecd0 u0a81 LAST idle change:cached procs:3 seq(0,0,0)}

at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
at android.app.ContextImpl.startService(ContextImpl.java:1477)
at android.content.ContextWrapper.startService(ContextWrapper.java:650)
at com.openlocate.android.core.OpenLocate.onFetchAdvertisingInfo(OpenLocate.java:611)
at com.openlocate.android.core.OpenLocate.access$1600(OpenLocate.java:60)
at com.openlocate.android.core.OpenLocate$2.onAdvertisingInfoTaskExecute(OpenLocate.java:544)
at com.openlocate.android.core.FetchAdvertisingInfoTask.onPostExecute(FetchAdvertisingInfoTask.java:65)
at com.openlocate.android.core.FetchAdvertisingInfoTask.onPostExecute(FetchAdvertisingInfoTask.java:34)
at android.os.AsyncTask.finish(AsyncTask.java:695)
at android.os.AsyncTask.-wrap1(Unknown Source:0)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by kurabi** [comment]
API 26 Support will be added soon. There is more things needed to be added per the `api_26_support` branch.

**Pull request merged**
